export const REGISTER_POST_REQUEST = "REGISTER_POST_REQUEST";
export const REGISTER_POST_SUCCESS = "REGISTER_POST_SUCCESS";
export const REGISTER_POST_FAILURE = "REGISTER_POST_FAILURE";


export const LOGIN_POST_REQUEST = "LOGIN_POST_REQUEST";
export const LOGIN_POST_SUCCESS = "LOGIN_POST_SUCCESS";
export const LOGIN_POST_FAILURE = "LOGIN_POST_FAILURE";